[build]
  command = "yarn build"
  functions = "functions"
  publish = "build"

[context.production.environment]
  TOKEN = "{access_token:ya29.GlvrBnCImILDrwAjzMq2rkvxE6Ex8StL9SnTCSgskSAdQnfTXrtybNeEYU574gsHayAevmLXgfV4QduUHdRh94MIGcJsp7boT_XrkxcdcK_DgRZAIA7TtBPZxopl,refresh_token:1/tJOLunTLM7MlvtCQlDSx5ZixMkSleVU3Qcra8GbC_J4,scope:https://www.googleapis.com/auth/calendar.readonly,token_type:Bearer,expiry_date:1555207789172}"
  CREDENTIALS = "{installed: {client_id: 701841266465-tofh1lmhavhkcnkej26akgn4vtm9203l.apps.googleusercontent.com,project_id: quickstart-1554758372424,auth_uri: https://accounts.google.com/o/oauth2/auth,token_uri: https://oauth2.googleapis.com/token,auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs,client_secret: ZJzqTwMqcp3ZJvMljfURbhlb,redirect_uris: [urn:ietf:wg:oauth:2.0:oob, http://localhost]}}"
  CALENDAR_ID = "k00j76b2k0p976p3uncsfqduo8@group.calendar.google.com"